name: Get Num Mods

# Controls when the workflow will run
on:
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '11 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write  # This grants write access to the repository

jobs:
  redraw:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install pandas matplotlib numpy

      - name: Run Graph Script
        run: |
          python graph.py

      - name: Commit and push data.csv and graph.png
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.csv graph.png
          git commit -m "Update num impressions" || echo "No changes to commit"
          git push
